set(OpenCV_DIR "~/Library/opencv/build/installed/share/OpenCV")
find_package(OpenCV REQUIRED)
message(STATUS ${GFLAGS_INCLUDE_DIR})
if (OpenCV_FOUND)
    include_directories(${OpenCV_INCLUDE_DIRS})
#    link_directories (${OpenCV_LIBS})
    message(STATUS "OpenCV version: ${OpenCV_VERSION}")
    message(STATUS "OoenCV libraries : ${OpenCV_LIBS}")
    link_libraries(${OpenCV_LIBS})
else()
    message(WARNING "Could not find OpenCV.")
endif()